### ISSUE TITLE
Compilation errors after a fresh clone

### ISSUE THREAD

**Issue by ghost** [mukul-rathi/gatsby-starter-reason-blog#3]
I can work through your blog explanation to try to get everything working on a new project on my own.

I created this issue to note that this starter isn't compiling for me currently.

**Comment by mukul-rathi** [comment]
Hi, thanks for filing the issue, I'm sorry to hear that the starter isn't compiling. 
Could you provide more detail? Which part isn't compiling? Do you have the compiler logs?

**Comment by ghost** [comment]
Closing for now, as I probably won't get around to reproducing and copying error here.

I managed to get everything working by cloning the latest gatsby starter and then incrementally applying the changes you describe as well as imitating the other changes you made in the source. The gatsby starter has some cosmetic differences since you converted it, but its pretty similar.

**Comment by ghost** [comment]
My internal notes as I converted the latest starter:
- itemScope property doesn't seem to work, even though it exists in reason react
- similarly, I didn't spend much effort trying to get data-is-root-path attribute to work
- some discrepancy between bsconfig package-specs.module value in blog versus in source code. i think the default recommendation has changed within reason/rescript as well
