### ISSUE TITLE
gatsby-plugin-mdx example?

### ISSUE THREAD

**Issue by ghost** [mukul-rathi/gatsby-starter-reason-blog#5]
I'm currently reading up on gatsby-plugin-mdx and I will probably make use of it. It might be useful to include how to use this in your starter? Feel free to close if you see this as out of scope.

I'll try to come back and add any notes about what I learned from attempting to use mdxjs.

**Comment by mukul-rathi** [comment]
Yes, this is out of scope - this starter's sole purpose is demonstrating Reason with Gatsby. 
MDX is great though!
